### PR TITLE
Dockerfile: Add new needed packages

### PR DESCRIPTION
**Pull request by kraj**
Rename git to git-core

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by cbrake** [comment]
I'll need to build and upload this image yet, unless you have already done so.

**Comment by kraj** [comment]
> I'll need to build and upload this image yet, unless you have already done so.

I have not yet done that.

**Comment by cbrake** [comment]
this is pushed now -- let me know if any problems:

https://hub.docker.com/layers/yoe-build/yoedistro/yoe-build/bullseye/images/sha256-e7353a7086fbc711f9d44127ef3e9f52a2f1c5b5fcfbbf4888aea05f4f9ab696?context=explore

**Comment by kraj** [comment]
I can push aarch64 as well can you detail the steps for me

**Pull request merged**
